name: CD

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: npm run build --if-present

      # - name: Upload to Server
      #   uses: appleboy/scp-action@master
      #   with: 
      #     host: ${{ secrets.REMOTE_HOST }}
      #     username: ${{ secrets.REMOTE_USERNAME }}
      #     key: ${{ secrets.PRIVATE_KEY }}
      #     source: ".next/,public/,package.json"
      #     target: "/home/ubuntu/ws/actiondemoe03"

      - name: Upload COS
        uses: zkqiang/tencent-cos-action@v0.1.0
        with:
          args: delete -r -f / && upload -r public / && upload -rs .next / && upload ./package.json /
          secret_id: ${{ secrets.SECRET_ID }}
          secret_key: ${{ secrets.SECRET_KEY }}
          bucket: github-action-1315390229
          region: ap-shanghai
      
      # - name: Restart Services(PM2 Reload)
      #   uses: appleboy/ssh-action@master
      #   with: 
      #     host: ${{ secrets.REMOTE_HOST }}
      #     username: ${{ secrets.REMOTE_USERNAME }}
      #     key: ${{ secrets.PRIVATE_KEY }}
      #     script: |
      #       cd /home/ubuntu/ws/actiondemoe03
      #       export NVM_DIR=~/.nvm
      #       source ~/.nvm/nvm.sh
      #       export NVM_NODEJS_ORG_MIRROR=https://npm.taobao.org/mirrors/node
      #       pnpm i
      #       pm2 reload actiondemo3
